tinyMCE.addI18n('en.emotions_dlg', {
    smile: "Smile",
    neutral: "Neutral",
    sad: "Sad",
    desc: "Emotions",
    title: "Add Emotion",
    usage: "Use left and right arrows to navigate.",
    "big_smile": "Big smile",
    yikes: "Yikes!",
    wink: "Wink",
    hmm: "Hmmm",
    "tongue_in_cheek": "Tongue in cheek",
    lol: "Laughing out loud",
    angry: "Angry",
    rolleyes: "Rolling eyes",
    cool: "Cool",
    blush: "Blush",
    aahh: "Aaahhh",
    smirk: "Smirk",
    huh: "Huh",
    barf: "Barf",
    thumbsup: "Thumbs up",
    whistle: "Whistle"
});
